[package]
name = "rustcontainer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.22.1"
rtnetlink = "0.8.0"
tokio = { version = "1.0.1", features = ["macros", "rt", "rt-multi-thread"] }